---
- name: install {{ ansible_distribution }} specific packages
  package:
    name:
      - 'dnf-command(versionlock)'
      - dnf-plugins-core
      - kernel-devel-matched
      - ntpsec
    state: latest
