---
- name: install {{ ansible_distribution }} specific packages
  package:
    name:
      - 'dnf-command(versionlock)'
      - dnf-plugins-core
      - kernel-devel-matched
      - ntpsec
    state: latest

- name: lock package to a version
  shell:
    cmd: dnf versionlock {{ item }}
  loop:
    - "datadog-agent-{{ dd_version }}"

- name: "List locked versions"
  shell: "dnf versionlock list"
  register: dnf_versionlock_list
- debug:
    msg: "{{ dnf_versionlock_list.stdout }}"
